---
- name: kubernetes-monitoring
  hosts: master-kuber
  gather_facts: false
  become: true
  vars:
    ansible_ssh_user: ubuntu

  tasks:
    - name: Just get information about the repository whether or not it has already been cloned locally
      ansible.builtin.git:
        repo: 'https://github.com/plusvaldis/kube-prometheus.git'
        dest: /home/ubuntu/monitoring_kubernetes
        clone: yes
        update: yes
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/ubuntu/monitoring_kubernetes
        owner: ubuntu
        group: ubuntu
    - name: delete files
      ansible.builtin.file:
        path: /home/ubuntu/monitoring_kubernetes/manifests/grafana-networkPolicy.yaml
        state: absent
    - name: delete files
      ansible.builtin.file:
        path: /home/ubuntu/monitoring_kubernetes/manifests/grafana-service.yaml
        state: absent    
    - name: create hosts file
      become: true
      copy:
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app.kubernetes.io/component: grafana
              app.kubernetes.io/name: grafana
              app.kubernetes.io/part-of: kube-prometheus
              app.kubernetes.io/version: 11.2.0
            name: grafana
            namespace: monitoring
          spec:
            ports:
            - name: http
              port: 3000
              targetPort: http
              nodePort: 30000
            selector:
              app.kubernetes.io/component: grafana
              app.kubernetes.io/name: grafana
              app.kubernetes.io/part-of: kube-prometheus
            type: NodePort
        dest: /home/ubuntu/monitoring_kubernetes/manifests/grafana-service.yaml
    - name: Execute shell command
      ansible.builtin.shell: kubectl apply --server-side -f /home/ubuntu/monitoring_kubernetes/manifests/setup -f /home/ubuntu/monitoring_kubernetes/manifests
